version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  fern-check:
    docker:
      - image: cimg/openjdk:11.0-node
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo npm install -g fern-api
          fern check
workflows:
  version: 2
  build:
    jobs:
      - fern-check:
          filters: { tags: { only: /.*/ } }