version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
  python: circleci/python@2.1.1
jobs:
  fern-check:
    docker:
      - image: cimg/openjdk:11.0-node
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo npm install -g fern-api
          fern check

  check:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: /home/circleci/.local/bin/poetry install --no-ansi
      - run:
          name: test
          command: /home/circleci/.local/bin/poetry run pytest -sv

  deploy-dev:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: cdk deploy
          command: |
            git_version="$(scripts/git-version.sh)"
            ./create_docker.sh "${git_version}"
            cd deploy
            npm install
            VERSION="${git_version}" npm run cdk deploy venus-dev --require-approval never --progress events

workflows:
  version: 2
  build:
    jobs:
      - fern-check:
          filters: { tags: { only: /.*/ } }

      - check:
          filters:
            tags:
              only: /.*/

      - test:
          filters:
            tags:
              only: /.*/

      - deploy-dev:
          filters:
            branches:
              only: main
          context:
            - aws
            - github
            - fern-dev
            - venus-dev
          requires:
            - check
            - test
